# Generated by Django 4.1.6 on 2023-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0005_alter_encuesta_age_alter_encuesta_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encuesta',
        ),
        migrations.RenameField(
            model_name='lugares',
            old_name='ubicacion',
            new_name='Zona',
        ),
        migrations.RemoveField(
            model_name='lugares',
            name='foto',
        ),
        migrations.AddField(
            model_name='lugares',
            name='cat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lugares',
            name='edad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
