# Generated by Django 4.1.6 on 2023-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0006_delete_encuesta_rename_ubicacion_lugares_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares',
            name='LvlEconomico',
            field=models.CharField(choices=[(1, 'menor que 50k'), (2, 'mayor que 50k')], max_length=50),
        ),
    ]
