# Generated by Django 4.1.6 on 2023-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0007_alter_lugares_lvleconomico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares',
            name='LvlEconomico',
            field=models.CharField(choices=[(1, 'menor que 50k'), (2, 'entre 50k y 150k'), (3, 'mas de 150k')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='Zona',
            field=models.CharField(choices=[(1, 'Envigado'), (2, 'Poblado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='cat',
            field=models.CharField(choices=[(1, 'Discoteca'), (2, 'Restaurante'), (3, 'Mirador')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='edad',
            field=models.CharField(choices=[(1, 'menor de edad'), (2, 'mayor de edad')], max_length=50, null=True),
        ),
    ]
