# Generated by Django 4.1.6 on 2023-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0008_alter_lugares_lvleconomico_alter_lugares_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares',
            name='LvlEconomico',
            field=models.CharField(choices=[('menor que 50k', 'menor que 50k'), ('entre 50k y 150k', 'entre 50k y 150k'), ('mas de 150k', 'mas de 150k')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='Zona',
            field=models.CharField(choices=[('Envigado', 'Envigado'), ('Poblado', 'Poblado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='cat',
            field=models.CharField(choices=[('Discoteca', 'Discoteca'), ('Restaurante', 'Restaurante'), ('Mirador', 'Mirador')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='edad',
            field=models.CharField(choices=[('menor de edad', 'menor de edad'), ('mayor de edad', 'mayor de edad')], max_length=50, null=True),
        ),
    ]
