# Generated by Django 4.1.6 on 2023-03-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0012_alter_lugares_categoria_alter_lugares_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lugares',
            new_name='lugar',
        ),
    ]
