# Generated by Django 4.1.6 on 2023-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0014_alter_lugar_lvleconomico_alter_lugar_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='foto',
            field=models.ImageField(default='', upload_to='Parcha-App/images/'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='LvlEconomico',
            field=models.CharField(choices=[('menor que 50k', 'menor que 50k'), ('entre 50k y 150k', 'entre 50k y 150k'), ('mas de 150k', 'mas de 150k')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='Zona',
            field=models.CharField(choices=[('Envigado', 'Envigado'), ('Poblado', 'Poblado')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='categoria',
            field=models.CharField(choices=[('Discoteca', 'Discoteca'), ('Restaurante', 'Restaurante'), ('Mirador', 'Mirador')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='descripcion',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='edad',
            field=models.CharField(choices=[('menor de edad', 'menor de edad'), ('mayor de edad', 'mayor de edad')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(default='x', max_length=50),
        ),
    ]
