# Generated by Django 4.1.6 on 2023-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0015_lugar_foto_alter_lugar_lvleconomico_alter_lugar_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='categoria',
            field=models.CharField(choices=[('Discoteca', 'Discoteca'), ('Restaurante', 'Restaurante'), ('Mirador', 'Mirador'), ('Centro Comercial', 'Centro Comercial')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
    ]
