# Generated by Django 4.1.7 on 2023-04-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0017_alter_lugar_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='ubicacion',
            field=models.ImageField(default='', upload_to='Parcha-App/images/'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='urlbi',
            field=models.URLField(default=''),
        ),
    ]
