# Generated by Django 4.1.6 on 2023-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0017_foro_alter_lugar_lvleconomico_alter_lugar_zona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='foro',
            name='puntaje',
            field=models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], default='', max_length=30),
        ),
    ]
