# Generated by Django 4.1.7 on 2023-04-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0018_lugar_ubicacion_lugar_urlbi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='urlbi',
            new_name='urlubi',
        ),
    ]
