# Generated by Django 4.1.6 on 2023-04-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0020_comentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foro',
            new_name='index',
        ),
        migrations.AddField(
            model_name='lugar',
            name='urlMapa',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
