# Generated by Django 4.1.6 on 2023-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0022_index_punt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='punt',
            field=models.URLField(default=''),
        ),
    ]
