# Generated by Django 4.1.6 on 2023-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0024_remove_index_punt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='punt',
            field=models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], default='', max_length=50),
        ),
    ]
