# Generated by Django 4.1.6 on 2023-05-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParchApp2', '0019_rename_urlbi_lugar_urlubi'),
        ('ParchApp2', '0027_remove_lugar_punt'),
    ]

    operations = [
    ]
